import { RGItem } from "./types";
import { WorkshopItem } from "~/types";
import { ProjectItem } from "./types";

// PROJECTS
export const projectItems: Array<ProjectItem> = [
  // OPEN PROJECTS
  {
    name: "Dermatological Image Analysis",
    desc: "Exploring multimodal foundation models for dermatological image analysis for acne grading and scar classification.",
    pm: "Ishaan Buddharaju",
    status: "open",
    commitment: "4-6",
    domain: ["Computer Vision", "Healthcare"],
    duration: "Spring 2026",
    advisor: "Dr. Josephine Nguyen",
  },
  {
    name: "Autonomous Drone Mapping",
    desc: "Mapping the world with drones autonomously. Requires C++/Python, robotics experience (SLAM), Linux CLI, VMs, and Docker.",
    pm: "Nathan Miller",
    status: "open",
    commitment: "4-6",
    domain: ["Computer Vision", "Process Control", "Robotics"],
    duration: "Spring 2026",
  },
  {
    name: "VGCRL",
    desc: "Using pretrained language models and transformers with reinforcement learning to play Pokémon Video Game Championship competitively.",
    pm: "Akkshay Rajan",
    status: "open",
    commitment: "3-5",
    domain: ["Reinforcement Learning"],
    duration: "Fall 2025 - Spring 2026",
  },
  {
    name: "Kalshi",
    desc: "Building an ML model to predict the weekly average amount of TSA check-ins in the US to place profitable bets on Kalshi.",
    pm: "Eubene In",
    status: "open",
    commitment: "4-5",
    domain: ["Finance", "Time Series Modelling"],
    duration: "Fall 2025 - Spring 2026",
  },
  {
    name: "AI Student Advisor",
    desc: "LLM chatbot that acts as a student advisor. Involves various flavors of RAG and NLP techniques.",
    pm: "Andrew Qiang",
    status: "open",
    commitment: "4-8",
    domain: ["Generative AI", "NLP", "Software Engineering"],
    duration: "Fall 2025 - Spring 2026",
  },
  {
    name: "Kaggle",
    desc: "Learning through participation in Kaggle Competitions. Requires basic Python and willingness to learn!",
    pm: "Arnav Mandal",
    status: "open",
    commitment: "3-4",
    domain: ["General"],
    duration: "Fall 2025 - Spring 2026",
  },
  // CLOSED PROJECTS
  {
    name: "DeepQuery",
    desc: "Benchmarking platform for AI search tools. Works with a YC startup.",
    pm: "Taaha Khan",
    status: "closed",
    commitment: "10",
    domain: ["Generative AI", "Software Engineering"],
    duration: "Fall 2025 - Spring 2026",
    advisor: "Lewis Polansky (Captain)",
  },
  {
    name: "NFL Predictive Resource Allocation",
    desc: "Predicting Team Success in the NFL.",
    pm: "Pranay Nandkeolyar",
    status: "closed",
    commitment: "3",
    domain: ["Time Series Modelling"],
    duration: "Fall 2025 - Spring 2026",
  },
  {
    name: "TE AI Cup 2025-2026",
    desc: "Scholarship project with TE Connectivity. Full year commitment.",
    pm: "Paul Jiang",
    status: "closed",
    commitment: "10",
    domain: ["Computer Vision", "Process Control"],
    duration: "Fall 2025 - Spring 2026",
    advisor: "Sonny Osunkwo",
  },
  {
    name: "Robot Vision",
    desc: "Computer vision algorithms for autonomous robotic navigation. Submits to industry challenges.",
    pm: "Manav Gagvani",
    status: "closed",
    commitment: "6-7",
    domain: ["Computer Vision", "Generative AI", "Robotics"],
    duration: "Fall 2025 - Spring 2026",
  },
];

// WORKSHOPS
// input most recent ones at top
export const workshopItems: Array<WorkshopItem> = [
  {
    date: "November 9, 2025",
    topic: "Intro to GPU Programming",
    leading: "Pranav Jadhav",
    status: "completed",
  },
  {
    date: "October 5, 2025",
    topic: "Building a Fullstack RAG Application",
    leading: "Pranav Jadhav (in collaboration with Purdue Stack)",
    status: "completed",
  },
  {
    date: "March 3, 2025",
    topic: "Diffusion Model from Scratch",
    leading: "Harmya Bhatt",
    status: "completed",
  },
  {
    date: "February 2, 2025",
    topic: "Neural Network from Scratch with NumPy",
    leading: "Pranav Jadhav",
    status: "completed",
  },
  {
    date: "October 19, 2024",
    topic: "Intro to CNNs",
    leading: "Harmya Bhatt",
    status: "completed",
  },
  {
    date: "September 30, 2024",
    topic: "Machine Learning Workshop",
    leading: "Harmya Bhatt in collaboration with Purdue MIND",
    status: "completed",
  },
  {
    date: "September 12, 2024",
    topic: "Intro to Neural Networks with PyTorch",
    leading: "Harmya Bhatt",
    status: "completed",
  },
  {
    date: "April 7, 2024",
    topic: "BERT",
    leading: "Brian S",
    status: "completed",
  },
  {
    date: "March 24, 2024",
    topic: "Transformer Architecture",
    leading: "Harmya Bhatt",
    status: "completed",
  },
  {
    date: "March 3, 2024",
    topic: "Large-Scale Training on HPC (SLURM)",
    leading: "Jinen Setpal",
    status: "completed",
  },
  {
    date: "February 20, 2024",
    topic: "CNNs and Transfer Learning",
    leading: "candysha",
    status: "completed",
  },
  {
    date: "February 4, 2024",
    topic: "Building a Basic Neural Network",
    leading: "Sagar Patil",
    status: "completed",
  },
];

// READING GROUPS
// input most recent ones at top
export const RGItems: Array<RGItem> = [
  {
    date: "February 19, 2026",
    topic: "Steering Vectors",
    leading: "Kabir Jain",
    status: "completed",
    room: "WALC 2127",
    domain: ["Theory"],
    slides: "https://drive.google.com/file/d/1b_-fDqS1euBtMB1JxY9UFPKLRpnNADmV/view?usp=sharing"
  },
  {
    date: "February 5, 2026",
    topic: "Modern Vision Transformers",
    leading: "Manav Gagvani",
    status: "completed",
    room: "WALC 2127",
    domain: ["CV"],
    slides: "https://drive.google.com/file/d/1HWrDCgeIXA7J_PrCQF_pNW0iyAUglvT1/view?usp=sharing"
  },
  {
    date: "January 29, 2026",
    topic: "Modern Attention Architectures",
    leading: "Alexandre Sauquet",
    status: "completed",
    room: "WALC 2127",
    domain: ["Theory", "NLP"],
    slides: "https://drive.google.com/file/d/1cx9Bm28anw8rHmURm-RaEE5uA2dE8eZB/view?usp=sharing"
  },
  {
    date: "December 4, 2025",
    topic: "Efficient Reasoning via Reward Model",
    leading: "Elijah D.",
    status: "completed",
    room: "LWSN B151",
    domain: ["Applied AI", "LLM", "RL"],
    slides: "https://drive.google.com/file/d/1IMjvxS90jZiqluHGlm5nabFvJ9TTZ_Y3/view?usp=sharing"
  },
  {
    date: "November 20, 2025",
    topic: "Inference Optimization Techniques",
    leading: "Shay Manor",
    status: "completed",
    room: "WALC 3132",
    domain: ["Applied AI", "Optimization"],
    slides: "https://drive.google.com/file/d/1DxrskSdykx9M4aXCuTQcwrv1SvtkpQF2/view?usp=sharing"
  },
  {
    date: "November 13, 2025",
    topic: "DeepSeek OCR",
    leading: "Oskar Jonientz",
    status: "completed",
    room: "WALC 3132",
    domain: ["Applied AI", "LLM"],
  },
  {
    date: "October 23, 2025",
    topic: "Optimizers",
    leading: "Alexandre Sauquet",
    status: "completed",
    room: "WALC 3132",
    domain: ["Theory", "Optimizers"],
    video: "https://youtu.be/llPtooDHF3s?si=GU7xrNAp3IJ2hHuv",
    slides: "https://drive.google.com/file/d/1wpd8o-6ILtq876r_pb5MxusR8IrDxFSI/view?usp=sharing"
  },
  {
    date: "October 9, 2025",
    topic: "BFGS",
    leading: "Alexandre Sauquet",
    status: "completed",
    room: "WALC 3132",
    domain: ["Theory", "Optimizers"],
    video: "https://youtu.be/uojMg0gC_1o?si=y5rJNM_kcHhzR4LR",
    slides: "https://drive.google.com/file/d/1ifhUc-ucXakdrL5aY_6jHHWKGuucelrP/view?usp=sharing"
  },
  {
    date: "October 2, 2025",
    topic: "Large Language Diffusion Models",
    leading: "Oskar Jonientz",
    status: "completed",
    room: "WALC 3132",
    domain: ["Theory", "CV"],
    video: "https://youtu.be/OAdYIWm4yS0?si=CnTAC-R8OkFGIzz6",
  },
  {
    date: "September 22, 2025",
    topic: "Byte Latent Transformers",
    leading: "Arnav Grover",
    status: "completed",
    room: "WALC 3132",
    domain: ["NLP"],
    slides: "https://docs.google.com/presentation/d/1vbhXnvhkoKzISZ3SV39-tpF263bvPd9HGlrcL8QrUgg"
  },
  {
    date: "September 9, 2025",
    topic: "3D Gaussian Splitting",
    leading: "Alexandre Sauquet",
    status: "completed",
    room: "WALC 3132",
    domain: ["Rendering"],
    video: "https://youtu.be/-1Y7AFLMDos?si=4xbWrdZtqezdDs-0",
    slides: "https://drive.google.com/file/d/1GKAeNIPlMRNdBF9VZ2DqiDcs0ZkmsRR8/view?usp=sharing"
  },
  {
    date: "April 24, 2025",
    topic: "Recurrent Depth LLMs",
    leading: "Alexandre Sauquet",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory", "Intrepretability"],
    video: "https://youtu.be/ZnPkZuPdsCg",
    slides: "https://docs.google.com/presentation/d/17_bTD-0bbImTNP_V99rmx5PxPbtp4aI6kPTbwkDdr8w/",
  },
  {
    date: "April 17, 2025",
    topic: "Optimal Transport [2/2]",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory", "Generative Models"],
    video: "https://youtu.be/QNMfLp6YOF0",
    slides: "https://jinen.setpal.net/slides/ot.pdf",
  },
  {
    date: "April 10, 2025",
    topic: "Optimal Transport [1/2]",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory", "Generative Models"],
    video: "https://youtu.be/5rGF7ytTjeI",
    slides: "https://jinen.setpal.net/slides/ot.pdf",
  },
  {
    date: "April 3, 2025",
    topic: "Cube: A Roblox View of 3D Intelligence",
    leading: "Nicholas Wade",
    status: "completed",
    room: "LWSN B151",
    domain: ["Applied AI", "3D", "Generative Models"],
    video: "https://youtu.be/0zGTDYgZ9d8",
    slides: "https://docs.google.com/presentation/d/1NqqAKYAdZisTfZGVArk0du1Y6wHDOuNJsTBKewLBJeQ/edit?usp=sharing",
  },
  {
    date: "March 27, 2025",
    topic: "Robot Foundation Models (RT1, RT2, OpenVLA)",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "LWSN B151",
    domain: ["Robotics"],
  },
  {
    date: "March 6, 2025",
    topic: "Neural Tangent Kernel",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory"],
    slides: "https://jinen.setpal.net/slides/ntk.pdf",
  },
  {
    date: "February 27, 2025",
    topic:
      "ZeRO: Memory Optimizations Toward Training Trillion Parameter Models",
    leading: "Saad Sharief",
    status: "completed",
    room: "LWSN B151",
    domain: ["Applied AI", "Engineering"],
  },
  {
    date: "February 20, 2025",
    topic: "Titans",
    leading: "Alexandre Sauquet",
    status: "completed",
    room: "LWSN B151",
    domain: ["NLP", "Theory"],
    video: "https://youtu.be/xwg6Ng3QsFE",
    slides: "https://docs.google.com/presentation/d/1Tuz9ycTU8U-wdV5pgbcsf874NaMLOx_7hCsITV8nJ0c/edit",
  },
  {
    date: "February 13, 2025",
    topic: "Sparse AutoEncoders",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["NLP", "Interpretability"],
    video: "https://youtu.be/_vUKIPYOaJw",
    slides: "https://jinen.setpal.net/slides/sae.pdf",
  },
  {
    date: "February 6, 2025",
    topic: "NVIDIA Cosmos",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "LWSN B151",
    domain: ["Robotics", "Applied AI", "Generative Models"],
    video: "https://youtu.be/xVGqFH7naWg",
    slides: "https://github.com/Abuynits/presentations/blob/main/nvidia_cosmos/main.pdf"
  },
  {
    date: "January 30, 2025",
    topic: "SoTA Approaches to Reasoning in LLMs — DeepSeek R1",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["Reinforcement Learning", "Applied AI", "Generative Models"],
    video: "https://youtu.be/MHwTvrAvYWs",
    slides: "https://jinen.setpal.net/slides/dsr1.pdf",
  },
  {
    date: "January 23, 2025",
    topic: "RoPE",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory", "Generative Models"],
    slides: "https://github.com/Abuynits/presentations/blob/main/rope/main.pdf",
  },
  {
    date: "November 21, 2024",
    topic: "Lumos : Empowering Multimodal LLMs with Scene Text Recognition",
    leading: "Adrien Qi",
    status: "completed",
    room: "WALC 2088",
    domain: ["Applied AI", "Vision", "NLP", "Generative Models"],
  },
  {
    date: "November 14, 2024",
    topic: "An Overview of Catastrophic AI Risks",
    leading: "Nathan Reed",
    status: "completed",
    room: "WALC 2088",
    domain: ["Safety"],
    video: "https://youtu.be/jLddV1GVaHw",
    slides: "https://docs.google.com/presentation/d/1e9A4aXTNtmA4v62UvG9MxFslEX1qxAGbaN_p0I2bNN8/edit",
  },
  {
    date: "November 7, 2024",
    topic: "Diffusion Policy for MPC",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "WALC 2088",
    domain: ["Applied AI", "Robotics", "Generative Models"],
    slides: "https://raw.githubusercontent.com/Abuynits/presentations/refs/heads/main/diffusion-policy/main.pdf",
  },
  {
    date: "October 24, 2024",
    topic: "AGOP for Deep Neural Collapse",
    leading: "Jinen Setpal",
    status: "completed",
    room: "WALC 2088",
    domain: ["Interpretability", "Theory"],
    video: "https://youtu.be/za8kA4GJDTQ",
    slides: "https://jinen.setpal.net/slides/dnc_by_agop.pdf",
  },
  {
    date: "October 10, 2024",
    topic: "Deep Neural Collapse",
    leading: "Jinen Setpal",
    status: "completed",
    room: "WALC 2088",
    domain: ["Interpretability", "Theory"],
    video: "https://youtu.be/DdxaSTnEcO0",
    slides: "https://jinen.setpal.net/slides/dnc_by_agop.pdf",
  },
  {
    date: "October 3, 2024",
    topic: "Graph Neural Network Explainer",
    leading: "Aaron",
    status: "completed",
    room: "WALC 2088",
    domain: ["Graph Learning"],
  },
  {
    date: "September 26, 2024",
    topic: "Group Transformation Invariance",
    leading: "Jinen Setpal",
    status: "completed",
    room: "WALC 2088",
    domain: ["Robustness", "Theory", "OOD Generalization"],
    slides: "https://jinen.setpal.net/slides/gti.pdf",
  },
  {
    date: "September 19, 2024",
    topic: "Physics Informed Machine Learning",
    leading: "Rohan Dekate",
    status: "completed",
    room: "WALC 2088",
    domain: ["Robustness", "Theory"],
    video: "https://youtu.be/q8I5I1m2_Bk",
    slides: "https://drive.google.com/file/d/1PfnTUDORtbox2E7_D94s2sq0Aa711RFr/view?usp=sharing",
  },
  {
    date: "September 11, 2024",
    topic: "Intro to Reinforcement Learning",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "WALC 2088",
    domain: ["Robotics", "Reinforcement Learning"],
  },
  {
    date: "September 3, 2024",
    topic: "Transformers (Rerun)",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B155",
    domain: ["Theory", "NLP"],
    slides: "https://jinen.setpal.net/slides/transformer.pdf",
  },
  {
    date: "August 29, 2024",
    topic: "GNN, Graphformer, Body Transformer",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "LWSN B134",
    domain: ["Graph Learning"],
  },
  {
    date: "April 18, 2024",
    topic: "Omnipredictors",
    leading: "Jinen Setpal",
    status: "completed",
    domain: ["Theory", "Robustness"],
    slides: "https://jinen.setpal.net/slides/omnipredictors.pdf",
  },
  {
    date: "March 28, 2024",
    topic: "DPO",
    leading: "Jinen Setpal",
    status: "completed",
    domain: ["Theory", "NLP", "Generative Models"],
    video: "https://youtu.be/RA1ddgkiWGM",
    slides: "https://jinen.setpal.net/slides/dpo.pdf",
  },
  {
    date: "March 21, 2024",
    topic: "LoRA",
    leading: "Ref",
    status: "completed",
    domain: ["Theory", "NLP"],
    slides: "https://docs.google.com/presentation/d/12Gn2dwzE2Iz5rxUhzHSz-dMQEUJFEOkO0X50LoVXIaU/edit",
  },
  {
    date: "March 7, 2024",
    topic: "DDPM & DDIM",
    leading: "Jeremy Lu",
    status: "completed",
    domain: ["Theory", "Vision", "Generative Models"],
    slides: "https://docs.google.com/presentation/d/1k7zUjKYO7Arl4gQLSOpl8f2OM7tGTQP_SnYu0mLSyQo/edit",
  },
  {
    date: "February 29, 2024",
    topic: "Version-Space Algebra Program Synthesis",
    leading: "Mikail K",
    status: "completed",
    domain: ["Theory", "PL"],
  },
  {
    date: "February 22, 2024",
    topic:
      "A Software-defined Tensor Streaming Multiprocessor for Large-scale Machine Learning",
    leading: "Saad Sharief",
    status: "completed",
    domain: ["Hardware"],
    video: "https://youtu.be/QcsCTI2cMFM",
    slides: "https://docs.google.com/presentation/d/1_x_rrHjlluqnWJ7zWhEoXampfGJgoCTy5jPywLpMLyM/edit#slide=id.p",
  },
  {
    date: "February 15, 2024",
    topic: "AI Inference in Production",
    leading: "Saad Sharief",
    status: "completed",
    domain: ["Deployment", "Applied AI"],
    video: "https://youtu.be/a3F6j2YCmcM",
    slides: "https://docs.google.com/presentation/d/1XYPXHWV4HgJ8eG6FAKU4MqzMfS7Wi8u44tK48kLLu9A/edit#slide=id.p",
  },
  {
    date: "February 8, 2024",
    topic: "Monosemanticity",
    leading: "Jinen Setpal",
    status: "completed",
    domain: ["Interpretability"],
    video: "https://youtu.be/WrqRpj2DCxw",
    slides: "https://jinen.setpal.net/slides/mechinterp.pdf",
  },
  {
    date: "February 1, 2024",
    topic: "Transformer Circuits",
    leading: "Jinen Setpal",
    status: "completed",
    domain: ["Interpretability", "Theory"],
    video: "https://youtu.be/NWKhKy1Vh8Q",
    slides: "https://jinen.setpal.net/slides/mechinterp.pdf",
  },
  {
    date: "January 25, 2024",
    topic: "Transformers",
    leading: "Alexiy Buynitsky",
    status: "completed",
    domain: ["Theory", "NLP"],
    video:
      "https://docs.google.com/document/d/1weXnv8kk9z9XILqVZF5Eg1WPy-eGr07O4OxZ5-MukzY/edit",
    slides: "https://docs.google.com/presentation/d/1EK8YH5TOiiya-H0lSzIm3phnxYeNCutf2dGUosCuwlY/edit",
  },
];
