import { RGItem } from "./types";
import { WorkshopItem } from "~/types";
import { ProjectItem } from "./types";

export const projectItems: Array<ProjectItem> = [
  {
    link: "https://github.com/PranayN23/NFLResourceAnalysis",
    name: "NFL Predicitve Resource Allocation",
    desc: "Scraped 10 more years of relevant nfl salary cap, performance, draft, and advanced analytical data and stored them into MongoDB. Created basic UIs for searching based on relevant player data.",
    pm: "Pranay Nandkeolyar",
    status: "closed",
    proficiency: "Beginner",
    domain: ["Time Series Modelling"],
    duration: "Fall 2024",
    memberInfo: "https://docs.google.com/spreadsheets/d/1BrO2emnEI6psEeNaZrsmL0Wwp-SL5hwEdpTG34ErwlM/edit?usp=sharing",
  },
  {
    name: "Kaggle",
    desc: "Learning through Participation in Kaggle Competitions.",
    pm: "Neil Sahai",
    status: "closed",
    proficiency: "Beginner",
    domain: ["General"],
    duration: "Fall 2024 + Spring 2025",
    memberInfo: "https://docs.google.com/spreadsheets/d/1iXUDsyLzoB7aPhIs960i16HsB-XWROdO_fJlzmVkhUA/edit?usp=sharing",
    accomplishments: ["Competed in 5+ Kaggle competitions with accuracy rates of upwards of 90%."],
  },
  {
    link: "https://www.theinboxpilot.com/",
    name: "InboxPilot",
    desc: "Over the year, the team was able to successfully develop a fully functional email assistant which allows users to create natural language rules, draft replies using personal context, semantically search an inbox, and handle email using voice. InboxPilot onboarded 15 beta users, processed over 4000 emails, and made over a 100 automatic drafts.",
    pm: "Rishi Mantri",
    status: "closed",
    proficiency: "Beginner",
    domain: ["NLP"],
    duration: "Fall 2024",
    memberInfo: "https://docs.google.com/spreadsheets/d/1axoeYkUT-WC_uLZZ1MDmPiJQfBhHkqINkFMpeb58eFc/edit?usp=sharing",
  },
  {
    name: "Geospacial Machine Learning Research Group [GeoML]",
    desc: "Pollutant concentration analysis from Satellite Data",
    pm: "Michael J. Wang",
    status: "closed",
    proficiency: "Intermediate",
    domain: ["Time Series Modelling", "Computer Vision"],
    duration: "Fall 2024 + Spring 2025",
    advisor: "Prof. Guang Lin, Dr. Gary Doran, Dr. Sina Hasheminassab",
    memberInfo: "https://docs.google.com/spreadsheets/d/16FAs44aVyDcLF_S8B9ZqsyMmEJP98LL1RL5mK3Rgqak/edit?usp=drive_link",
  },
  {
    link: "https://www.trine.edu/innovation-one/aimm/winners.aspx",
    name: "AIMM ICC",
    desc: "Creating an unmanned autonomous boat that can complete complex tasks",
    pm: "Nicholas Wade",
    status: "closed",
    proficiency: "Intermediate",
    domain: ["Process Control", "Computer Vision"],
    memberInfo: "https://docs.google.com/spreadsheets/d/1DwIMw7RrkFmX49ZkZCin6s6-WuL4-Qbt1CeX-CzUKes/edit?usp=sharing",
    accomplishments: ["2nd Place Trine AIMM ICC competition"],
  },
  {
    name: "PokeRI",
    desc: "DeepRL for Pokemon Battling",
    pm: "Kevin Wang",
    status: "closed",
    proficiency: "Intermediate",
    domain: ["Reinforcement Learning"],
    duration: "Fall 2024",
    memberInfo: "https://docs.google.com/spreadsheets/d/1Y8ne9Sd2sSYp3ZUnvT8z1kZBL4PpwDj4ojAjCNmkwiw/edit?usp=sharing",
  },
  {
    name: "SWAT: Students Winning at Algo Trading",
    desc: "Algorithmic Trading Competitive Team",
    pm: "Yohaan Chokhany",
    status: "closed",
    proficiency: "Intermediate",
    domain: ["Finance"],
    memberInfo: "https://docs.google.com/spreadsheets/d/1ancxMFSFhrRXvLnslGnoTBjTdfD3rlVcdPBTEmG3vj0/edit?usp=sharing",
  },
  {
    name: "Drone Vision",
    desc: "The team successfully generated a synthetic dataset of images taken from in the middle of urban scenes. They used Meta Segment Anything (SAM) model to generate masks, out of which they selected relevant classes, and used the MMSegmentation library to train a new semantic segmentation model.",
    pm: "Manav Gagani",
    status: "closed",
    proficiency: "Intermediate",
    domain: ["Computer Vision", "Segmentation", "Object Detection"],
    duration: "Fall 2024 + Spring 2025",
    memberInfo: "https://docs.google.com/spreadsheets/d/1ebeAdjMo2XRojZZ19xloosyoWY1_6ggUHwn-tXB_ilY/edit?usp=sharing",
  },
  {
    name: "TE AI Cup 2024-2025",
    desc: "Developed a novel industrial solution backed by a state-of-the-art learning method in academic research.",
    pm: "Daniel Park",
    status: "closed",
    proficiency: "Advanced",
    domain: ["Process Control", "Computer Vision"],
    duration: "Fall 2024 + Spring 2025",
    advisor: "Sonny Osunkwo",
    memberInfo: "https://docs.google.com/spreadsheets/d/1im0FjZLBWWyVQxM2imX2Ngd8s8qV9HTOeXQrJR1ZBmo/edit?usp=sharing",
    accomplishments: ["Nationally 2nd", "Globally 3rd", "Patent", "Academic Paper"],
  },
  {
    name: "AI Student Advisor",
    desc: "LLM chatbot that acts as a student advisor",
    pm: "Andrew Qiang",
    status: "closed",
    domain: ["NLP"],
    duration: "Fall 2024",
    memberInfo: "https://docs.google.com/spreadsheets/d/1sZ4v9iwCEvijWEUFRMNC82FE8sn0g_Z0KF2f6PMBdb4/edit?usp=drive_link",
  },
]

// WORKSHOPS
// input most recent ones at top
export const workshopItems: Array<WorkshopItem> = [
  { 
    date: "September 12, 2024",
    topic: "Intro to Neural Networks with PyTorch",
    leading: "Harmya Bhatt",
    status: "completed",
  },
  {
    date: "April 7, 2024",
    topic: "BERT",
    leading: "Brian S",
    status: "completed",
  },
  {
    date: "March 24, 2024",
    topic: "Transformer Architecture",
    leading: "Harmya Bhatt",
    status: "completed",
  },
  {
    date: "March 3, 2024",
    topic: "Large-Scale Training on HPC (SLURM)",
    leading: "Jinen Setpal",
    status: "completed",
  },
  {
    date: "February 20, 2024",
    topic: "CNNs and Transfer Learning",
    leading: "candysha",
    status: "completed",
  },
  {
    date: "February 4, 2024",
    topic: "Building a Basic Neural Network",
    leading: "Sagar Patil",
    status: "completed",
  },
];

// READING GROUPS
// input most recent ones at top
export const RGItems: Array<RGItem> = [
  { 
    date: "April 24, 2025",
    topic: "Recurrent Depth LLMs",
    leading: "Alexandre Sauquet",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory", "Intrepretability"],
    extra: "https://youtu.be/ZnPkZuPdsCg",
  },
  { 
    date: "April 17, 2025",
    topic: "Optimal Transport [2/2]",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory", "Generative Models"],
    extra: "https://youtu.be/QNMfLp6YOF0",
  },
  { 
    date: "April 10, 2025",
    topic: "Optimal Transport [1/2]",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory", "Generative Models"],
    extra: "https://youtu.be/5rGF7ytTjeI",
  },
  { 
    date: "April 3, 2025",
    topic: "Cube: A Roblox View of 3D Intelligence",
    leading: "Nicholas Wade",
    status: "completed",
    room: "LWSN B151",
    domain: ["Applied AI", "3D", "Generative Models"],
    extra: "https://youtu.be/0zGTDYgZ9d8",
  },
  { 
    date: "March 27, 2025",
    topic: "Robot Foundation Models (RT1, RT2, OpenVLA)",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "LWSN B151",
    domain: ["Robotics"],
  },
  { 
    date: "March 6, 2025",
    topic: "Neural Tangent Kernel",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory"],
  },
  { 
    date: "February 27, 2025",
    topic: "ZeRO: Memory Optimizations Toward Training Trillion Parameter Models",
    leading: "Saad Sharief",
    status: "completed",
    room: "LWSN B151",
    domain: ["Applied AI", "Engineering"],
  },
  { 
    date: "February 20, 2025",
    topic: "Titans",
    leading: "Alexandre Sauquet",
    status: "completed",
    room: "LWSN B151",
    domain: ["NLP", "Theory"],
    extra: "https://youtu.be/xwg6Ng3QsFE",
  },
  { 
    date: "February 13, 2025",
    topic: "Sparse AutoEncoders",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["NLP", "Interpretability"],
    extra: "https://youtu.be/_vUKIPYOaJw",
  },
  { 
    date: "February 6, 2025",
    topic: "NVIDIA Cosmos",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "LWSN B151",
    domain: ["Robotics", "Applied AI", "Generative Models"],
    extra: "https://youtu.be/xVGqFH7naWg",
  },
  { 
    date: "January 30, 2025",
    topic: "SoTA Approaches to Reasoning in LLMs — DeepSeek R1",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B151",
    domain: ["Reinforcement Learning", "Applied AI", "Generative Models"],
    extra: "https://youtu.be/MHwTvrAvYWs",
  },
  { 
    date: "January 23, 2025",
    topic: "RoPE",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "LWSN B151",
    domain: ["Theory", "Generative Models"],
  },
  { 
    date: "November 21, 2024",
    topic: "Lumos : Empowering Multimodal LLMs with Scene Text Recognition",
    leading: "Adrien Qi",
    status: "completed",
    room: "WALC 2088",
    domain: ["Applied AI", "Vision", "NLP", "Generative Models"],
  },
  { 
    date: "November 14, 2024",
    topic: "An Overview of Catastrophic AI Risks",
    leading: "Nathan Reed",
    status: "completed",
    room: "WALC 2088",
    domain: ["Safety"],
    extra: "https://youtu.be/jLddV1GVaHw",
  },
  { 
    date: "November 7, 2024",
    topic: "Diffusion Policy for MPC",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "WALC 2088",
    domain: ["Applied AI", "Robotics", "Generative Models"],
  },
  { 
    date: "October 24, 2024",
    topic: "AGOP for Deep Neural Collapse",
    leading: "Jinen Setpal",
    status: "completed",
    room: "WALC 2088",
    domain: ["Interpretability", "Theory"],
    extra: "https://youtu.be/za8kA4GJDTQ",
  },
  { 
    date: "October 10, 2024",
    topic: "Deep Neural Collapse",
    leading: "Jinen Setpal",
    status: "completed",
    room: "WALC 2088",
    domain: ["Interpretability", "Theory"],
    extra: "https://youtu.be/DdxaSTnEcO0",
  },
  { 
    date: "October 3, 2024",
    topic: "Graph Neural Network Explainer",
    leading: "Aaron",
    status: "completed",
    room: "WALC 2088",
    domain: ["Graph Learning"],
  },
  { 
    date: "September 26, 2024",
    topic: "Group Transformation Invariance",
    leading: "Jinen Setpal",
    status: "completed",
    room: "WALC 2088",
    domain: ["Robustness", "Theory", "OOD Generalization"],
  },
  { 
    date: "September 19, 2024",
    topic: "Physics Informed Machine Learning",
    leading: "Rohan Dekate",
    status: "completed",
    room: "WALC 2088",
    domain: ["Robustness", "Theory"],
    extra: "https://youtu.be/q8I5I1m2_Bk",
  },
  { 
    date: "September 11, 2024",
    topic: "Intro to Reinforcement Learning",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "WALC 2088",
    domain: ["Robotics", "Reinforcement Learning"],
  },
  { 
    date: "September 3, 2024",
    topic: "Transformers (Rerun)",
    leading: "Jinen Setpal",
    status: "completed",
    room: "LWSN B155",
    domain: ["Theory", "NLP"],
  },
  { 
    date: "August 29, 2024",
    topic: "GNN, Graphformer, Body Transformer",
    leading: "Alexiy Buynitsky",
    status: "completed",
    room: "LWSN B134",
    domain: ["Graph Learning"],
  },
  { 
    date: "April 18, 2024",
    topic: "Omnipredictors",
    leading: "Jinen Setpal",
    status: "completed",
    domain: ["Theory", "Robustness"],
  },
  { 
    date: "March 28, 2024",
    topic: "DPO",
    leading: "Jinen Setpal",
    status: "completed",
    domain: ["Theory", "NLP", "Generative Models"],
    extra: "https://youtu.be/RA1ddgkiWGM",
  },
  { 
    date: "March 21, 2024",
    topic: "LoRA",
    leading: "Ref",
    status: "completed",
    domain: ["Theory", "NLP"],
  },
  { 
    date: "March 7, 2024",
    topic: "DDPM & DDIM",
    leading: "Jeremy Lu",
    status: "completed",
    domain: ["Theory", "Vision", "Generative Models"],
  },
  { 
    date: "February 29, 2024",
    topic: "Version-Space Algebra Program Synthesis",
    leading: "Mikail K",
    status: "completed",
    domain: ["Theory", "PL"],
  },
  { 
    date: "February 22, 2024",
    topic: "A Software-defined Tensor Streaming Multiprocessor for Large-scale Machine Learning",
    leading: "Saad Sharief",
    status: "completed",
    domain: ["Hardware"],
    extra: "https://youtu.be/QcsCTI2cMFM",
  },
  { 
    date: "February 15, 2024",
    topic: "AI Inference in Production",
    leading: "Saad Sharief",
    status: "completed",
    domain: ["Deployment", "Applied AI"],
    extra: "https://youtu.be/a3F6j2YCmcM",
  },
  { 
    date: "February 8, 2024",
    topic: "Monosemanticity",
    leading: "Jinen Setpal",
    status: "completed",
    domain: ["Interpretability"],
    extra: "https://youtu.be/WrqRpj2DCxw",
  },
  { 
    date: "February 1, 2024",
    topic: "Transformer Circuits",
    leading: "Jinen Setpal",
    status: "completed",
    domain: ["Interpretability", "Theory"],
    extra: "https://youtu.be/NWKhKy1Vh8Q",
  },
  { 
    date: "January 25, 2024",
    topic: "Transformers",
    leading: "Alexiy Buynitsky",
    status: "completed",
    domain: ["Theory", "NLP"],
    extra: "https://docs.google.com/document/d/1weXnv8kk9z9XILqVZF5Eg1WPy-eGr07O4OxZ5-MukzY/edit",
  },
];